plugins: lyrics missing zero bandcamp discogs inline duplicates hook

directory: /mnt/e/Artists/

import:
    write: yes
    copy: no
    move: yes

clutter: ["Thumbs.DB", ".DS_Store", "*.m3u", ".pls", "*.jpg", "*.png"]

ignore: [".*", "*~", "System Volume Information"]

threaded: yes

timeout: 5.0

match:
    strong_rec_thresh: 0.10

original_date: yes

replace:
    '[\\/]': _
    '^\.': _
    '[\x00-\x1f]': _
    '[<>:"\?\*\|]': _
    '\.$': _
    '\s+$': ''
    '^\s+': ''
    '^-': _

hook:
    hooks:
        - event: album_imported
          command: python3 /mnt/d/Audio/mov.py {album.path}
          
item_fields:
    first_letter: |
        import re
        if re.match("[0-9]", albumartist[0]):
            return "#"
        elif re.match("[^\w]", albumartist[0]):
            return "$"
        else:
            return albumartist[0].upper()

album_fields:
    format_name_probably: |
        if items[0].format.upper() == "MP3":
            total_bitrate = 0
            for item in items:
                total_bitrate += item.bitrate
            average_bitrate = total_bitrate / len(items) / 1000
            if average_bitrate == 320:
                return "320"
            elif average_bitrate >= 200:
                return "V0"
            elif average_bitrate == 192:
                return "192"
            elif average_bitrate == 160:
                return "160"
            elif average_bitrate == 128:
                return "128"
            else:
                return "TOO LOW FIND NEW SOURCE"
        else:
            return items[0].format

paths:
    default: $first_letter/$albumartist/$album ($year) [%if{$bitdepth,$bitdepth-Bit $format,$format $format_name_probably}]/$track. $title
    singleton:  $first_letter/$albumartist/$title ($year) [%if{$bitdepth,$bitdepth-Bit $format,$format $format_name_probably}]/$title
    comp: VA/$album ($year) [%if{$bitdepth,$bitdepth-Bit $format,$format $format_name_probably}]/$track. $artist - $title

zero:
    keep_fields: title artist album albumartist year track disc lyrics itunesadvisory genre genres images art
    # keep_fields: title artist album albumartist year track disc lyrics itunesadvisory genre genres rg_track_gain rg_album_gain rg_track_peak rg_album_peak images art
    update_database: true

bandcamp:
    lyrics: true
    art: false
